
import helvaticaFont from "./fonts/helvaticaFont";
import "./globals.css";
import Grain from "@/components/Grain";


export const metadata = {
  title: "Saad Hasan - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${helvaticaFont.className} bg-black`}>
        {children}
        <Grain />
      </body>
    </html>
  );
}
